config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :agents do
  	get :show_image, on: :member
  end
end

app/models/agent.rb
class Agent < ApplicationRecord
	validates :name, presence: true, length: { minimum: 5 }
	validates :image, presence: true

	enum status: { enabled:  1 , disabled:  2 }


	def image_size
    errors[:image] << "should be less than 1MB" if image.size > 1.megabytes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.human_enum_name(enum_name, enum_value)
    I18n.t("activerecord.attributes.#{model_name.i18n_key}.#{enum_name.to_s.pluralize}.#{enum_value}")
  end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController

  def index
    @agents = Agent.all
  end

  def new
    @agent = Agent.new
  end

  def create
    puts 'create called'
    logger.debug('create hitted')
    name = agent_params[:name]
    image = agent_params[:image].read
    if agent_params[:status] == 1
      disabled_at = nil
    else
      disabled_at = Date.today
    end
    logger.debug(disabled_at)
    @agent = Agent.new
    @agent.name = name
    @agent.image = image
    @agent.disabled_at = disabled_at
 
    if @agent.save
      redirect_to agents_url
    else
      render 'new'
    end
  end

  def edit
    @agent = Agent.find(params[:id ])
  end

  def update
    @agent = Agent.find(params[:id])
    name = agent_params[:name]
    image = agent_params[:image].read
    if agent_params[:status].to_i == 1
      disabled_at = nil
    else
      disabled_at = Date.today
    end
    
    logger.debug(disabled_at)
    @agent.name = name
    @agent.image = image
    @agent.disabled_at = disabled_at
 
    if @agent.save
      redirect_to agents_url
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @agent = Agent.find(params[:id ])
    @agent.destroy
 
    redirect_to agents_url
  end

  def show_image 
    agent = Agent.find(params[:id ]) 
    send_data agent.image,  type: 'image/*', disposition: 'inline' 
  end

private
  def agent_params
    params.require(:agent).permit(:name, :image, :status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agents/_form.html.erb
<%= form_with(scope: :agent, model: @agent, url: url, local: true) do |form| %>

<% if @agent.nil? && @agent.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@agent.errors.count, "error") %> prohibited
        this agent from being saved:
      </h2>
      <ul>
        <% @agent.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :image %><br>
    <%= form.file_field :image , required: true%>
  </p>

    <p>
    <%= form.label :status %><br>
    <%= form.select(:status , options_for_select(Agent.statuses.map { |key, value| [Agent.human_enum_name(:status, key.to_s), value]}, @agent.disabled_at.nil? ? 1 : 2), include_blank: true ) %>
    <!-- <%= form.select(:status , options_for_select([['enabled', 1], ['disabled', 2]], @agent.disabled_at.nil? ? 1 : 2), include_blank: true ) %> -->
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/agents/edit.html.erb
<h1>Agents#EDIT</h1>
<p><img src="<%= show_image_agent_path(@agent)%>" width= 60px, height=60px, style="border-radius: 50%"/></p>
<%= render 'form', model: @agent, url: agent_path %>

app/views/agents/index.html.erb
<h1>Agents#index</h1>
<p>
	<%= link_to 'Create New', new_agent_path %>
</p>
<table>
  <tr>
    <th>Name</th>
    <th>image</th>
    <th>status</th>
    <th>Edit/delete</th>
  </tr>
 
  <% @agents.each do |agent| %>
    <tr>
      <td><%= agent.name %></td>
      <td><img src="<%= show_image_agent_path(agent)%>" width= 60px, height=60px, style="border-radius: 50%"/></td>
      <td><%= agent.disabled_at.nil? ? Agent.human_enum_name(:status, Agent.statuses.key(1).to_s) : 
      Agent.human_enum_name(:status, Agent.statuses.key(2).to_s) %></td>
      <td><%= link_to 'Edit', edit_agent_path(agent) %>
      <%= link_to 'Delete', agent_path(agent), method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/agents/new.html.erb
<h1>Agents#new</h1>
<%= render 'form', url: agents_path %>

app/views/agents/show.html.erb
<h1>Agents#show</h1>
<p>Find me in app/views/agents/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learning</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>